Legg til sms hendelse
navikt/rekrutteringsbistand-kandidat pull request #356
Opened 2021-12-06 08:05 UTC by joarau

2021-12-06 15:46 UTC, joarau commented on src/kandidatliste/kandidatrad/status-og-hendelser/hendelser/SmsSendt.tsx
> +        return <div></div>;
Burde jeg returnere noe annet her?

2021-12-07 06:49 UTC, kjesvale requested changes
La til en liten kommentar, ellers ser det fint ut!

Har du sagt til Malin at SMS-hendelsen alltid vil havne under "Ny kandidat" nå? Det er helt sikkert bra i en første versjon, hvis det brukes mest på jobbmesse-stillinger. På sikt burde vi vurdere å sortere alle hendelsene på dato, men tenker det er unødvendig nå.

2021-12-07 06:49 UTC, kjesvale commented on src/kandidatliste/kandidatrad/status-og-hendelser/hendelser/SmsSendt.tsx
> +        return <div></div>;
Ja, jeg ville hatt en early return på null

```
if (!sms) {
    return null;
}
```

2021-12-07 06:49 UTC, kjesvale commented on src/kandidatliste/kandidatrad/status-og-hendelser/hendelser/SmsSendt.tsx
> +        return <div></div>;
Ellers må nettleseren rendre en unødvendig `div`

2021-12-10 08:40 UTC, merged